id: IB72A33FF
legacy_id: P004605
ocr_import_info:
  bdrc_scan_id: W1KG10872
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T03:38:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:59:06.168012+00:00'
last_modified: 2022-08-31 11:00:04.452181
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10872
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10872
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངོར་མཁན་ཆེན་དཔལ་ལྡན་ཆོས་སྐྱོང་ཞབས་ཀྱི་རྣམ་ཐར། ༼སྡེ་དགེ་པར་མ།༽
  author: ཞུ་ཆེན་ཚུལ་ཁྲིམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.5026069617141221
  ocr_word_median_confidence_index: 0.46000000834465027
quality: null
bases:
  I1KG11673:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11673
      total_pages: 836
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11673.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.5060186724823179
    legacy_id: v001
  I1KG11674:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11674
      total_pages: 986
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG11674.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.49952372483259333
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
